language: c
jdk:
- openjdk7
install:
- "./travis-tool.sh install_deps"
- sudo R CMD javareconf
- "./travis-tool.sh install_r yaml rJava RJDBC RPostgreSQL testthat knitr devtools"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
before_script:
- psql -c 'create database travis;' -U postgres
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: fBrHwMoboLH0pv/xqCA6aiSQRpFkKz0K+eqXtywJGhsHl3abt+BdzsEsBqwoTZxNplrpnR+UcH3IWSE/ijL5turjJgyBs/SouwxE+8o1Zuwx8ILRlsTe82RK5+PifvXc3n4BHX00U2N8pjiPqNkY3to9KvjIercYYVpCfXv4V8s=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
